server:
  port: 8888

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
